/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/call-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List call groups
         * @description Returns deduplicated call groups (calls from multiple recorders grouped together)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start time filter (RFC3339) */
                    start_time?: string;
                    /** @description End time filter (RFC3339) */
                    end_time?: string;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.CallGroupListResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/call-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a call group
         * @description Returns a call group with all its individual call recordings
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Call group ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.CallGroupDetailResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all calls
         * @description Returns call recordings with optional filters
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by system ID (database ID) */
                    system?: number;
                    /** @description Filter by P25 SYSID (e.g., '348') */
                    sysid?: string;
                    /** @description Filter by talkgroup ID */
                    talkgroup?: number;
                    /** @description Start time filter (RFC3339) */
                    start_time?: string;
                    /** @description End time filter (RFC3339) */
                    end_time?: string;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.CallListResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active calls
         * @description Returns currently active calls (calls without a stop_time)
         */
        get: {
            parameters: {
                query?: {
                    /** @description System ID or short_name */
                    system?: string;
                    /** @description System short name */
                    sys_name?: string;
                    /** @description Filter by talkgroup ID */
                    talkgroup?: number;
                    /** @description Filter by emergency status */
                    emergency?: boolean;
                    /** @description Filter by encryption status */
                    encrypted?: boolean;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.CallListResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/active/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get real-time active calls
         * @description Returns currently active calls from in-memory tracker (real-time from MQTT)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recently ended calls
         * @description Returns recently completed calls from database with full unit list and audio status. Deduplication is enabled by default (one call per call group). Use deduplicate=false to show all recordings including simulcast duplicates.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of calls to return */
                    limit?: number;
                    /** @description Deduplicate by call_group (show one per group) */
                    deduplicate?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a call
         * @description Returns a single call by its trunk-recorder call ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Trunk-recorder call ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Call"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get call audio
         * @description Streams the audio file for a call
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Trunk-recorder call ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/mp4": string;
                        "audio/mpeg": string;
                        "audio/ogg": string;
                        "audio/wav": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/mp4": components["schemas"]["rest.ErrorResponse"];
                        "audio/mpeg": components["schemas"]["rest.ErrorResponse"];
                        "audio/ogg": components["schemas"]["rest.ErrorResponse"];
                        "audio/wav": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/mp4": components["schemas"]["rest.ErrorResponse"];
                        "audio/mpeg": components["schemas"]["rest.ErrorResponse"];
                        "audio/ogg": components["schemas"]["rest.ErrorResponse"];
                        "audio/wav": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/mp4": components["schemas"]["rest.ErrorResponse"];
                        "audio/mpeg": components["schemas"]["rest.ErrorResponse"];
                        "audio/ogg": components["schemas"]["rest.ErrorResponse"];
                        "audio/wav": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{id}/frequencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get call frequencies
         * @description Returns the list of frequency entries (freqList) within a call, ordered by position in the audio
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Trunk-recorder call ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Response with frequencies array and count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{id}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue call for transcription
         * @description Queues a call for transcription (or re-transcription)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Call ID (tr_call_id or numeric ID) */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["rest.TranscribeCallRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{id}/transcription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get call transcription
         * @description Returns the transcription for a specific call
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Call ID (tr_call_id or numeric ID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Transcription"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{id}/transmissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get call transmissions
         * @description Returns the list of unit transmissions (srcList) within a call, ordered by position in the audio
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Trunk-recorder call ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Response with transmissions array and count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/p25-systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List P25 systems
         * @description Returns P25 systems grouped by sysid+wacn. Each P25 system may have multiple sites (trunk-recorder instances monitoring different NACs on the same network).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recorders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recorder states
         * @description Returns all known recorder states from in-memory cache (populated by MQTT recorder messages)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.RecorderListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system statistics
         * @description Returns overall system statistics including counts and call metrics
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get activity summary
         * @description Returns summary statistics and recent activity across all systems
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ActivityResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get decode rates
         * @description Returns system decode rate measurements over time
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start time filter (RFC3339) */
                    start_time?: string;
                    /** @description End time filter (RFC3339) */
                    end_time?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.RatesResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recording sites
         * @description Returns all trunk-recorder recording sites. Each site monitors one radio system/site combination. For P25 networks with multiple sites, use /p25-systems to see them grouped by sysid+wacn.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.SiteListResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a recording site
         * @description Returns a single recording site by system_id
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description System ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.Site"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{id}/talkgroups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List system talkgroups
         * @description Returns all talkgroups for a specific system
         */
        get: {
            parameters: {
                query?: {
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description System ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.TalkgroupListResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/talkgroups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all talkgroups
         * @description Returns all talkgroups with stats (call_count, calls_1h, calls_24h, unit_count). Optionally filtered by SYSID. When searching, results include relevance_score (100=exact, 50=prefix, 10=contains).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by SYSID (P25 system identifier) */
                    sysid?: string;
                    /** @description Search by alpha_tag, tgid, group, tag, or description */
                    search?: string;
                    /** @description Sort field: alpha_tag, tgid, last_seen, first_seen, group, call_count, calls_1h, calls_24h, unit_count, relevance */
                    sort?: string;
                    /** @description Sort direction: asc, desc */
                    sort_dir?: string;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.TalkgroupListResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/talkgroups/encryption-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get encryption stats per talkgroup
         * @description Returns counts of encrypted and clear calls per talkgroup from recent activity
         */
        get: {
            parameters: {
                query?: {
                    /** @description Hours of history to include (default 24) */
                    hours?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/talkgroups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a talkgroup
         * @description Returns a single talkgroup with stats (call_count, calls_1h, calls_24h, unit_count). Accepts sysid:tgid format (e.g., "348:9178") or plain tgid (returns 409 if ambiguous)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Talkgroup ID (sysid:tgid or plain tgid) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Talkgroup"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Ambiguous tgid exists in multiple systems */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/talkgroups/{id}/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List talkgroup calls
         * @description Returns calls for a specific talkgroup. Accepts sysid:tgid format (e.g., "348:9178") or plain tgid.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start time filter (RFC3339) */
                    start_time?: string;
                    /** @description End time filter (RFC3339) */
                    end_time?: string;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Talkgroup ID (sysid:tgid or plain tgid) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.CallListResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcription/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transcription queue status
         * @description Returns statistics about the transcription queue
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["database.TranscriptionQueueStats"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcriptions/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent transcriptions
         * @description Returns recently created transcriptions with call context
         */
        get: {
            parameters: {
                query?: {
                    /** @description Max results */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcriptions/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search transcriptions
         * @description Full-text search across all transcriptions
         */
        get: {
            parameters: {
                query: {
                    /** @description Search query */
                    q: string;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all units
         * @description Returns all radio units, optionally filtered by SYSID. When searching, results include relevance_score (100=exact, 50=prefix, 10=contains).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by SYSID (P25 system identifier) */
                    sysid?: string;
                    /** @description Search by alpha_tag or unit_id */
                    search?: string;
                    /** @description Sort field: alpha_tag, unit_id, last_seen, first_seen, relevance */
                    sort?: string;
                    /** @description Sort direction: asc, desc */
                    sort_dir?: string;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.UnitListResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active units
         * @description Returns units that have had recent activity within the specified time window
         */
        get: {
            parameters: {
                query?: {
                    /** @description Activity window in minutes (1-60) */
                    window?: number;
                    /** @description Filter by SYSID (P25 system identifier) */
                    sysid?: string;
                    /** @description System ID or short_name (deprecated, use sysid) */
                    system?: string;
                    /** @description System short name */
                    sys_name?: string;
                    /** @description Filter by talkgroup ID */
                    talkgroup?: number;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ActiveUnitListResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a unit
         * @description Returns a single unit. Accepts sysid:unit_id format (e.g., "348:1234567") or plain unit_id (returns 409 if ambiguous across systems)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unit ID (sysid:unit_id or plain unit_id) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.Unit"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Ambiguous unit_id exists in multiple systems */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List unit calls
         * @description Returns calls that include transmissions from a specific unit. Accepts sysid:unit_id format (e.g., "348:902001") or plain unit_id.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start time filter (RFC3339) */
                    start_time?: string;
                    /** @description End time filter (RFC3339) */
                    end_time?: string;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Unit ID (sysid:unit_id or plain unit_id) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.CallListResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List unit events
         * @description Returns events (affiliations, registrations, etc.) for a specific unit by radio ID
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by event type (on, off, join, call, etc.) */
                    type?: string;
                    /** @description Filter by talkgroup ID (TGID) */
                    talkgroup?: number;
                    /** @description Start time filter (RFC3339) */
                    start_time?: string;
                    /** @description End time filter (RFC3339) */
                    end_time?: string;
                    /** @description Results per page */
                    limit?: number;
                    /** @description Page offset */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Unit radio ID (RID) */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.UnitEventListResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rest.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "database.TranscriptionQueueStats": {
            completed?: number;
            failed?: number;
            pending?: number;
            processing?: number;
        };
        "ingest.RecorderInfo": {
            count?: number;
            duration?: number;
            freq?: number;
            rec_num?: number;
            rec_state_type?: string;
            rec_type?: string;
            recorder_id?: number;
            squelched?: boolean;
            src_num?: number;
            state?: number;
            tg_alpha_tag?: string;
            tgid?: number;
            unit_alpha_tag?: string;
            unit_id?: number;
        };
        /** @description A recorded radio call/transmission */
        "models.Call": {
            /** @example false */
            analog?: boolean;
            /**
             * @description Audio
             * @example butco/2024/01/15/1001-1705319400.m4a
             */
            audio_path?: string;
            /** @example 45000 */
            audio_size?: number;
            /** @example digital */
            audio_type?: string;
            /** @example /api/v1/calls/123/audio */
            audio_url?: string;
            /** @example 1 */
            call_group_id?: number;
            /**
             * @description Identifiers
             * @example 348:9173:1769997011
             */
            call_id?: string;
            /**
             * @description Status
             * @example 3
             */
            call_state?: number;
            /** @example false */
            conventional?: boolean;
            /** @example 45.5 */
            duration?: number;
            /** @example false */
            emergency?: boolean;
            /** @example false */
            encrypted?: boolean;
            /** @example 2 */
            error_count?: number;
            /**
             * @description Quality
             * @example 851012500
             */
            freq?: number;
            /** @example 0 */
            freq_error?: number;
            /**
             * @description Transcription fields (populated by queries)
             * @example true
             */
            has_transcription?: boolean;
            /** @description Metadata */
            metadata_json?: Record<string, never>;
            /** @example 0 */
            mon_state?: number;
            /** @example -80 */
            noise_db?: number;
            /** @description Patches */
            patched_tgids?: number[];
            /** @example false */
            phase2_tdma?: boolean;
            /** @example -45.5 */
            signal_db?: number;
            /** @example 0 */
            spike_count?: number;
            /**
             * @description Timing
             * @example 2024-01-15T10:30:00Z
             */
            start_time?: string;
            /** @example 2024-01-15T10:30:45Z */
            stop_time?: string;
            /** @example 0 */
            tdma_slot?: number;
            /** @example 09-8L Main */
            tg_alpha_tag?: string;
            /** @example 348 */
            tg_sysid?: string;
            /**
             * @description Joined fields (not stored in calls table)
             * @example 9178
             */
            tgid?: number;
            /** @example Engine 5 responding to the scene */
            transcription_text?: string;
            /** @example 6 */
            transcription_word_count?: number;
            units?: components["schemas"]["models.CallUnit"][];
        };
        "models.CallUnit": {
            /** @example 09 7COM3 */
            alpha_tag?: string;
            /** @example 924003 */
            unit_rid?: number;
        };
        /** @description A talkgroup on a radio system, unique within a SYSID */
        "models.Talkgroup": {
            /** @example Fire Dispatch */
            alpha_tag?: string;
            /**
             * @description Stats (populated by list/detail queries)
             * @example 1547
             */
            call_count?: number;
            /** @example 12 */
            calls_1h?: number;
            /** @example 234 */
            calls_24h?: number;
            /** @example County Fire Dispatch Channel */
            description?: string;
            /** @example 2024-01-01T00:00:00Z */
            first_seen?: string;
            /** @example Fire */
            group?: string;
            /** @example 2024-01-15T12:30:00Z */
            last_seen?: string;
            /** @example D */
            mode?: string;
            /** @example 1 */
            priority?: number;
            /** @example 348 */
            sysid?: string;
            /** @example Fire Dispatch */
            tag?: string;
            /** @example 1001 */
            tgid?: number;
            /** @example 45 */
            unit_count?: number;
        };
        /** @description A transcription of a radio call's audio content */
        "models.Transcription": {
            /**
             * @description seconds, for word timeline rendering
             * @example 15.5
             */
            call_duration?: number;
            /** @example 123 */
            call_id?: number;
            /** @example 0.95 */
            confidence?: number;
            /** @example 2024-01-15T12:30:00Z */
            created_at?: string;
            /** @example 1500 */
            duration_ms?: number;
            /** @example 1 */
            id?: number;
            /** @example en */
            language?: string;
            /** @example whisper-1 */
            model?: string;
            /** @example openai */
            provider?: string;
            /** @example Engine 5 responding to the scene */
            text?: string;
            /** @example 6 */
            word_count?: number;
            words?: components["schemas"]["models.TranscriptionWord"][];
        };
        /** @description A word from the transcription with start and end times */
        "models.TranscriptionWord": {
            /**
             * @description seconds from start of audio
             * @example 0.85
             */
            end?: number;
            /**
             * @description seconds from start of audio
             * @example 0.5
             */
            start?: number;
            /** @example Engine */
            word?: string;
        };
        /** @description A radio unit (mobile or portable radio), unique within a SYSID */
        "models.Unit": {
            /** @example Engine 1 */
            alpha_tag?: string;
            /** @example radioreference */
            alpha_tag_source?: string;
            /** @example 2024-01-01T00:00:00Z */
            first_seen?: string;
            /** @example 09-8L Main */
            last_event_tg_tag?: string;
            /** @example 9178 */
            last_event_tgid?: number;
            last_event_time?: string;
            /**
             * @description Joined fields (not stored in units table)
             * @example call
             */
            last_event_type?: string;
            /** @example 2024-01-15T12:30:00Z */
            last_seen?: string;
            /** @example 348 */
            sysid?: string;
            /** @example 1234567 */
            unit_id?: number;
        };
        /** @description A unit event such as registration, affiliation, or call activity */
        "models.UnitEvent": {
            /** @example join */
            event_type?: string;
            /** @example 1 */
            id?: number;
            /** @example 1 */
            instance_id?: number;
            metadata_json?: Record<string, never>;
            /** @example 1 */
            system_id?: number;
            /** @example 348 */
            tg_sysid?: string;
            /** @example 1001 */
            tgid?: number;
            /** @example 2024-01-15T10:30:00Z */
            time?: string;
            /** @example 1234567 */
            unit_rid?: number;
            /** @example 348 */
            unit_sysid?: string;
        };
        "rest.ActiveUnitListResponse": {
            /** @example 10 */
            count?: number;
            /** @example 50 */
            limit?: number;
            /** @example 0 */
            offset?: number;
            units?: unknown;
            /** @example 5 */
            window?: number;
        };
        "rest.ActivityResponse": {
            /** @example 5000 */
            calls_24h?: number;
            system_activity?: unknown;
            /** @example 3 */
            systems?: number;
            /** @example 500 */
            talkgroups?: number;
            /** @example 1000 */
            units?: number;
        };
        "rest.CallGroupDetailResponse": {
            call_group?: unknown;
            calls?: unknown;
        };
        "rest.CallGroupListResponse": {
            call_groups?: unknown;
            /** @example 50 */
            count?: number;
            /** @example 50 */
            limit?: number;
            /** @example 0 */
            offset?: number;
        };
        "rest.CallListResponse": {
            calls?: unknown;
            /** @example 25 */
            count?: number;
            /** @example 50 */
            limit?: number;
            /** @example 0 */
            offset?: number;
        };
        "rest.ErrorResponse": {
            /** @example Resource not found */
            error?: string;
        };
        "rest.RatesResponse": {
            /** @example 100 */
            count?: number;
            rates?: unknown;
        };
        "rest.RecorderListResponse": {
            /** @example 12 */
            count?: number;
            recorders?: components["schemas"]["ingest.RecorderInfo"][];
        };
        /** @description A trunk-recorder recording site. Note: "system_id" is the database ID used in API calls. */
        "rest.Site": {
            /**
             * @description Deprecated: use system_id
             * @example 1
             */
            id?: number;
            /**
             * @description Trunk-recorder instance
             * @example 1
             */
            instance_id?: number;
            /**
             * @description P25 NAC (site-specific)
             * @example 340
             */
            nac?: string;
            /**
             * @description P25 RFSS
             * @example 4
             */
            rfss?: number;
            /**
             * @description Trunk-recorder short name
             * @example butco
             */
            short_name?: string;
            /**
             * @description P25 Site ID
             * @example 1
             */
            site_id?: number;
            /**
             * @description System number within TR config
             * @example 0
             */
            sys_num?: number;
            /**
             * @description P25 System ID (hex)
             * @example 348
             */
            sysid?: string;
            /**
             * @description Database ID, use this in API calls
             * @example 1
             */
            system_id?: number;
            /**
             * @description p25, smartnet, conventional
             * @example p25
             */
            system_type?: string;
            /**
             * @description P25 WACN
             * @example BEE00
             */
            wacn?: string;
        };
        /** @description List of trunk-recorder recording sites. Each site monitors one radio system/site combination. */
        "rest.SiteListResponse": {
            /** @example 2 */
            count?: number;
            sites?: components["schemas"]["rest.Site"][];
        };
        "rest.TalkgroupListResponse": {
            /** @example 100 */
            count?: number;
            /** @example 50 */
            limit?: number;
            /** @example 0 */
            offset?: number;
            talkgroups?: unknown;
        };
        "rest.TranscribeCallRequest": {
            priority?: number;
        };
        "rest.UnitEventListResponse": {
            /** @example 100 */
            count?: number;
            events?: components["schemas"]["models.UnitEvent"][];
            /** @example 50 */
            limit?: number;
            /** @example 0 */
            offset?: number;
        };
        "rest.UnitListResponse": {
            /** @example 50 */
            count?: number;
            /** @example 50 */
            limit?: number;
            /** @example 0 */
            offset?: number;
            units?: components["schemas"]["models.Unit"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
